### ISSUE TITLE
Request to consider adding New Computer Modern Math fonts, especially the Sans Math font

### ISSUE THREAD

**Issue by apoorvpotnis** [fred-wang/MathFonts#15]
Recently, New Computer Modern Sans Math font has been released. The serif fonts provide a slightly thicker Book weight and a Bold Math font as well. The coverage of glyphs is excellent; it contains all the Unicode math glyphs, plus more.

Link: https://ctan.org/pkg/newcomputermodern

**Comment by fred-wang** [comment]
Thanks for the report. That looks interesting.

A PR is welcome :-)

**Comment by apoorvpotnis** [comment]
I think a new release has not been created, and thus not deployed to the website. I don't see NewCM fonts or Lete Sans in the dropdown menu on https://fred-wang.github.io/MathFonts/.

**Comment by norbusan** [comment]
@apoorvpotnis In my case it already selects the Book weight from the local font ;-) It seems fontconfig already prefers to book variant, since I get:
```
$ fc-match NewComputerModernMath
NewCMMath-Book.otf: "NewComputerModernMath" "Book"
```
but `fc-list | grep NewCMMath` returns both the Regular and the Book variant.

So I think the only change - and a good idea - is to switch to the Book font for url downloads, so that url and local defined fonts behave the same way. 
Thanks for pointing it out.

@fred-wang Related question: How far should I add text fonts (regular/italic/bold/bolditalic) to ComputerModern (and also LeteMath?)

I prepare PRs for all the above issues.

**Comment by norbusan** [comment]
@apoorvpotnis Send PR for fixing this, see link above. You can try it out at https://www.preining.info/MathFonts/

**Comment by apoorvpotnis** [comment]
> @apoorvpotnis Send PR for fixing this, see link above. You can try it out at https://www.preining.info/MathFonts/

So I have changed all instances of the `Regular` to `Book` in the `mathfonts.css` file from the NewComputerModern folder. This is correct, right?

**Comment by apoorvpotnis** [comment]
Nevermind, Commit 5363c71 fixes this.
