### ISSUE TITLE
Include Libertinus Sans files

### ISSUE THREAD

**Issue by pyfisch** [fred-wang/MathFonts#8]
The [Libertinus font](https://github.com/khaledhosny/libertinus) not only includes serif and math characters but also a sans-serif version of the font. It would be great if these files were also packed by MathFonts.

**Comment by fred-wang** [comment]
The main goal of this repository is to provide math fonts. For that purpose it's nice to have the accompanying serif text fonts,. Packaging the whole set of fonts is up to the upstream maintainers.  So I'm closing this bug as WONTFIX. For Libertinus, I think @khaledhosny only wants to release OTF fonts since it's easy to generate the WOFF ones anyway...
